carts/urls.py
from django.urls import path
from .views import (cart_home,
                    cart_update,
                    checkout_home,
                    checkout_complete)
app_name = 'cart'
urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('checkout/success', checkout_complete, name='checkout_complete'),
]

products/urls.py
from django.urls import path
from .views import (ProductListView,
                    ProductDetailSlugView)
app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view(),name='list'),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name='detail'),
]

templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/master.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

templates/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/1e1fe36689.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.6/jsrender.js" integrity="sha512-DtWD/uCp2x1mspIw6vhZGPuJP85aKEL0HFI0jFVxcEiWw1OHJn36LqtkX9G9chzKVYLtTT0G8uJ2miDEL7ucTQ==" crossorigin="anonymous"></script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'js/ecommerce.js' %}"></script>
<script src="{% static 'js/csrf_ajax.js' %}"></script>
<script src="{% static 'js/ecommerce_billing.js' %}"></script>

templates/base/js_templates.html
{% verbatim %}
	<script id="stripeTemplate" type="text/x-jsrender">
		<form class="form payment-form" id="payment-form" data-token={{:publishKey}}
			data-next-url={{:nextUrl}}>
			<div class="form-row">
			<label for="card-element">
			  <p class="lead" style="margin: 0;padding: 0">Credit or debit card</p>
			</label>
			<div id="card-element" class="form-control">
			  <!-- A Stripe Element will be inserted here. -->
			</div>

			<!-- Used to display Element errors. -->
			<div id="card-errors" role="alert"></div>
			</div>
		  	<button class="btn btn-success my-2 btn-load">{{:btnTitle}}</button>
		</form>
	</script>
{% endverbatim %}

templates/base/navbar.html
{% url 'about' as about %}
{% url 'contact' as contact %}
{% url 'products:list' as productsurl %}
{% url 'logout' as logout %}
{% url 'register' as register %}
{% url 'cart:home' as cart %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'img/cart.png' %}" height="50" class="d-inline-block align-center" alt="" loading="lazy" style='padding-right:10px'>
    eCommerce
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% comment %} <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li> {% endcomment %}
      <li class="nav-item {%if request.path == about%}active{%endif%}">
        <a class="nav-link" href="{% url 'about' %}">About Us</a>
      </li>
      <li class="nav-item {%if request.path == contact%}active{%endif%}">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
      <li class="nav-item {%if request.path == productsurl %}active{%endif%}">
        <a class="nav-link" href="{% url 'products:list' %}">Products</a>
      </li>
      {%if not request.user.is_authenticated%}
      <li class="nav-item {%if request.path == login%}active{%endif%}">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item {%if request.path == register%}active{%endif%}">
        <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
      </li>
      {% else %}
      <li class="nav-item {%if request.path == logout%}active{%endif%}">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      {%endif%}
      <li class="nav-item {%if request.path == cart%}active{%endif%}">
        <a class="nav-link" href="{% url 'cart:home' %}">
          <i class="fas fa-shopping-cart" area-hidden=True></i>
          <span class="navbar_item_count">
          {{ request.session.cart_items }}</a>
          </span>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>