carts/urls.py
from django.urls import path
from .views import (cart_home,
                    cart_update,
                    checkout_home,
                    checkout_complete)
app_name = 'cart'
urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('checkout/success', checkout_complete, name='checkout_complete'),
]

search/urls.py
from django.urls import path
from .views import SearchProductView

app_name = 'search'
urlpatterns = [
    path('', SearchProductView.as_view(), name='query'),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.views.generic import ListView
# noinspection PyUnresolvedReferences
from products.models import Product


class SearchProductView(ListView):
    template_name = "search/view.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        search_query = request.GET.get('q')
        try:
            length = len(search_query)
        except:
            length = 0
        if search_query is not None and length != 0:
            return Product.objects.search(query=search_query)
        else:
            return Product.objects.filter(featured=True)

search/templates/search/snippets/search-form.html
<form class="form my-2 my-lg-0 search-form" method="get" action="{% url 'search:query' %}">
    <div class="input-group">
        <input aria-label="Search"
               class="form-control mr-sm-1"
               name='q'
               placeholder="Search Products"
               type="search"
               value="{{request.GET.q}}"
               autocomplete="off" />
        <span class="input-group-btn disabled">
            <button class="btn btn-success" type="submit">Search</button>
        </span>
    </div>
</form>